import { PRODUCT_LIST_DEFAULTS } from '../../lib/productDisplayDefaults';
import { Product } from './CartContext';

export const products: Product[] = [
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '1',
    name: 'Shadow Pullover',
    price: 4500,
    category: 'Non Zip',
    colors: ['#0A0A0A', '#2C2C2C', '#1a1a1a'],
    image: 'https://picsum.photos/600/800?grayscale&random=10',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '2',
    name: 'Asphalt Zip',
    price: 5200,
    category: 'Zip-up',
    colors: ['#2C2C2C', '#4a4a4a'],
    image: 'https://picsum.photos/600/800?grayscale&random=11',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '3',
    name: 'Crimson Oversized',
    price: 6500,
    category: 'Limited Edition',
    colors: ['#C0392B', '#0A0A0A'],
    image: 'https://picsum.photos/600/800?grayscale&random=12',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '4',
    name: 'Phantom Hood',
    price: 5800,
    category: 'Non Zip',
    colors: ['#0A0A0A', '#F0EDE8'],
    image: 'https://picsum.photos/600/800?grayscale&random=13',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '5',
    name: 'Stealth Zip Hood',
    price: 4800,
    category: 'Zip-up',
    colors: ['#0A0A0A', '#2C2C2C', '#1a1a1a'],
    image: 'https://picsum.photos/600/800?grayscale&random=14',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '6',
    name: 'Street Noir Limited',
    price: 7500,
    category: 'Limited Edition',
    colors: ['#0A0A0A', '#C0392B', '#F0EDE8'],
    image: 'https://picsum.photos/600/800?grayscale&random=15',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '7',
    name: 'Urban Pullover',
    price: 4200,
    category: 'Non Zip',
    colors: ['#2C2C2C', '#0A0A0A'],
    image: 'https://picsum.photos/600/800?grayscale&random=16',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '8',
    name: 'Velocity Zip',
    price: 5500,
    category: 'Zip-up',
    colors: ['#C0392B', '#0A0A0A', '#2C2C2C'],
    image: 'https://picsum.photos/600/800?grayscale&random=17',
  },
  {
    ...PRODUCT_LIST_DEFAULTS,
    id: '9',
    name: 'Eclipse Rare',
    price: 8200,
    category: 'Limited Edition',
    colors: ['#0A0A0A', '#2C2C2C', '#C0392B'],
    image: 'https://picsum.photos/600/800?grayscale&random=18',
  },
];
